### ISSUE TITLE
Rule for some sort of references

### ISSUE THREAD

**Issue by k0nserv** [jonallured/danger-commit_lint#19]
Hey @jonallured,

I'm checking in to see if you'd be open to me adding a rule looking for a "reference" at the start of the commit. We use a convention at work for JIRA ticket references. It looks like this

```
[ABC-123] Implement thing
```

Where `ABC-123` is a reference to the JIRA card that the commit relates to. For commits that don't have a reference we use something like `[No-JIRA]` or `[None]`. Would you be open to me adding something like this.

Unrelated: Is there anything in the plugin that currently makes it GitHub only or should it work with any git host?

**Comment by jonallured** [comment]
Hey @k0nserv, that sounds like a neat check for Danger to make, but I don't think it fits in with what I want this plugin to do. Feel free to fork or whatever, but I would like to see this plugin grow no larger. ❤️ 

Re: this plugin and working with any git host - I just skimmed the codebase again and I didn't see anything that would be an issue. 👍

**Comment by k0nserv** [comment]
Okay that's reasonable, I was thinking about consuming danger-commit_lint as a gem to be able to reuse the rules and extended it without changing danger-commit_lint itself as an alternative

**Comment by jonallured** [comment]
Yeah, you probably just want to check out this part:

https://github.com/jonallured/danger-commit_lint/blob/master/lib/commit_lint/plugin.rb#L120

That'll pretty much get you where you want to be, I think.

**Comment by k0nserv** [comment]
Cool 👍 Thanks for your help 💜
