### ISSUE TITLE
Group warnings

### ISSUE THREAD

**Issue by DrPhil** [jonallured/danger-commit_lint#26]
Thank you so much for creating this Danger Plugin. I think it's very useful. Unfortunately my first interaction looked something like this:

><table>
>  <thead>
>    <tr>
>      <th width="50"></th>
>      <th width="100%" data-danger-table="true">Warnings</th>
>    </tr>
>  </thead>
>  <tbody><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit1</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit2</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit3</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit4</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit5</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit6</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit7</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit8</td>
>    </tr>
>  
><tr>
>      <td>:warning:</td>
>      <td>Please start commit subject with capital letter. commit9</td>
>    </tr>
>  </tbody>
></table>

I was in love in first sight, but I think most people would have preferred something less repetitive:

><table>
>  <thead>
>    <tr>
>      <th width="50"></th>
>      <th width="100%" data-danger-table="true">Warnings</th>
>    </tr>
>  </thead>
>  <tbody><tr>
>      <td>:warning:</td>
>      <td>Please start commit subjects with capital letter. <br />
>  commit1  commit2  commit3  commit4  commit5  commit6  commit7  commit8  commit9
></td>
>    </tr>
>  </tbody>
></table>

I've not tried ruby before, would you still be up for a PR?

**Comment by jonallured** [comment]
Closing this one with #27
