### ISSUE TITLE
Make subject_length configurable

### ISSUE THREAD

**Issue by Jeehut** [jonallured/danger-commit_lint#28]
I understand that the default length is set to 50, but I think this plugin would be much more useful if it was more flexible. While turning on and off and setting the level (warning/failure) is possible, I think for `subject_length` there should also be a possibility to configure a different limit than `50` which is of course a community best practice, but nevertheless a "magic number" that might not be working for everyone. For example I prefer to have a limit of `80` in my projects for various reasons I think I should not need to explain here.

**Comment by jonallured** [comment]
At a philosophical level I disagree with this idea because this plugin is opinionated and tries very hard to enforce standard commit message hygiene. That said, if you wanted to extract a configurable setting for this I would probably merge that PR. I'm practical even though I'm also idealistic. 😝

**Comment by Jeehut** [comment]
@jonallured Actually I have opted for the 50 characters limit by now for our projects as well and the team got used to it quickly. So for me this is not needed anymore. I'll close it, but thanks for taking the time to answer, much appreciated! 👍
