### ISSUE TITLE
Add link to Git's "Commit Guidelines"

### ISSUE THREAD

**Issue by mokagio** [jonallured/danger-commit_lint#6]
I often get asked _"why should I write my commits like this?!"_, in which case I try to redirect people to [Git's Commit Guidelines](https://www.git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#Commit-Guidelines).

It might be useful to add a link to this in the README?

**Comment by jonallured** [comment]
Great idea, thanks for the link!! ❤️  ❤️  ❤️
