### ISSUE TITLE
Support for Danger 4.0

### ISSUE THREAD

**Issue by nikolaykasyanov** [jonallured/danger-commit_lint#8]
Currently this gem is locked to 3.0: https://github.com/jonallured/danger-commit_lint/blob/05c6e9bb406041ed7bfb85567b790c720be27a4c/danger-commit_lint.gemspec#L21

Thank you!

**Comment by jonallured** [comment]
Thanks for opening this issue - I've been meaning to get to this and it was the kick I needed to do it. New gem has been pushed and you should be good to go! 😄
