### ISSUE TITLE
Include commit hash and link in output table

### ISSUE THREAD

**Issue by suchow** [jonallured/danger-commit_lint#9]
When this plugin detects an issue in a PR with multiple commits, it is not immediately obvious which line of the table applies to which commit:

![image](https://cloud.githubusercontent.com/assets/613981/21272486/78ac5f24-c38d-11e6-9516-f08dd56eb7d9.png)

I'd like to propose that each line of the output include a short version of commit hash, linked to its GitHub URL.

**Comment by jonallured** [comment]
Oh wow, not helpful! I think you're absolutely right that the offending SHA would be a good addition to the output. I think I have an idea about how to do it, but it'll take a little tinkering.

Great suggestion!! 😄

**Comment by jonallured** [comment]
Ok, I've got this on master now - should have a new gem version cut here pretty soon. Thanks again for the idea and let me know if you have any feedback on this one!!
